---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [2]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

df.index[0]

'Afghanistan'

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [2]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero() 

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [24]:
def answer_one():
    return df.sort(['Gold'],ascending=False).index[0]

/opt/conda/lib/python3.6/site-packages/ipykernel/__main__.py:6: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)


'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [12]:
def answer_two():
    df['W_S_GOLD_diff']=df['Gold']-df['Gold.1']
    return df.sort(['W_S_GOLD_diff'],ascending=False).index[0]

/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:6: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)


# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
United States         26   976     757     666   2399        22      96   
Soviet Union           9   395     319     296   1010         9      78   
Great Britain         27   236     272     272    780        22      10   
China                  9   201     146     126    473        10      12   
France                27   202     223     246    671        22      31   
Hungary               25   167     144     165    476        22       0   
Italy                 26   198     166     185    549        22      37   
Australia             25   139     152     177    468        18       5   
Japan                 21   130     126     142    398        20      10   
East Germany           5   153     129     127    409         6      39   
Germany               15   174     182     217    573        11      78   
Sweden                26   143     164     176    483        22      50   
Romania               20    88      94     119    301        20       0   
Russia                 5   132     121     142    395         6      49   
Cuba                  19    72      67      70    209         0       0   
Finland               24   101      84     117    302        22      42   
Poland                20    64      82     125    271        22       6   
South Korea           16    81      82      80    243        17      26   
Bulgaria              19    51      85      78    214        19       1   
Czechoslovakia        16    49      49      45    143        16       2   
West Germany           5    56      67      81    204         6      11   
Denmark               26    43      68      68    179        13       0   
New Zealand           22    42      18      39     99        15       0   
Netherlands           25    77      85     104    266        20      37   
Turkey                21    39      25      24     88        16       0   
Unified Team           1    45      38      29    112         1       9   
Spain                 22    37      59      35    131        19       1   
Belgium               25    37      52      53    142        20       1   
Ukraine                5    33      27      55    115         6       2   
Greece                27    30      42      39    111        18       0   
...                  ...   ...     ...     ...    ...       ...     ...   
Iceland               19     0       2       2      4        17       0   
Barbados              11     0       0       1      1         0       0   
Sudan                 11     0       1       0      1         0       0   
Sri Lanka             16     0       2       0      2         0       0   
Macedonia              5     0       0       1      1         5       0   
Djibouti               7     0       0       1      1         0       0   
Eritrea                4     0       0       1      1         0       0   
Paraguay              11     0       1       0      1         1       0   
Namibia                6     0       4       0      4         0       0   
Philippines           20     0       2       7      9         4       0   
Cyprus                 9     0       1       0      1        10       0   
Puerto Rico           17     0       2       6      8         6       0   
Qatar                  8     0       0       4      4         0       0   
Ivory Coast           12     0       1       0      1         0       0   
Gabon                  9     0       1       0      1         0       0   
Iraq                  13     0       0       1      1         0       0   
Montenegro             2     0       1       0      1         2       0   
Moldova                5     0       2       5      7         6       0   
Saudi Arabia          10     0       1       2      3         0       0   
Senegal               13     0       1       0      1         5       0   
Ghana                 13     0       1       3      4         1       0   
Mauritius              8     0       0   

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [14]:
def answer_three():
    df['W_S_G_ral_G']= (df['Gold']-df['Gold.1'])/(df['Gold.2'])
    return df[(df['Gold']>0) & (df['Gold.1']>0)].sort(['W_S_G_ral_G'],ascending=False).index[0]

/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:7: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)


'Bulgaria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [18]:
def answer_four():
    df['Points'] = df['Gold.2'] * 3 + df['Silver.2'] * 2 + df['Bronze.2']
    return df['Points']

146

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [183]:
census_df = pd.read_csv('census.csv')
census_df = census_df[census_df['SUMLEV'] == 50]

census_df.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   
5      50       3         6      1       9  Alabama   Blount County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        
5          57322              57322            57373     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   
5          1.807375         -1.177622         -1.748766         -2.062535   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   
5         -1.369970     1.859511    -0.848580    -1.402476    -1.577232   

   RNETMIG2015  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  
5    -0.884411  

[5 rows x 100 columns]

In [191]:
def answer_five():
    return census_df['STNAME'].value_counts().argmax()

answer_five()

'Texas'

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [125]:
def answer_six():
    census_df = pd.read_csv('census.csv')
    census_df = census_df[census_df['SUMLEV'] == 50]
    census_df = census_df.set_index(['STNAME'])
    a = {}
    for x in census_df['STATE'].unique():
        l=census_df[census_df['STATE'] == x ]['CENSUS2010POP'].nlargest(3).sum()
        a[l] = census_df[census_df['STATE'] == x ]['STATE'].index[0]

    census_df = census_df.reset_index()
    b = []
    b = [a[i] for i in sorted(a.keys(), reverse = True)[0:3]]
    return b
   
#x = census_df.loc[name].sort(['CENSUS2010POP'],ascending=False)
#a.append([name, sum(x.iloc[1:4]['CENSUS2010POP'])])


#census_df[census_df['SUMLEV'] == 50].groupby(
#    'STNAME')['CENSUS2010POP'].apply(
#    lambda x: x.nlargest(3).sum()).nlargest(
#   3).index.values.tolist()


['California', 'Texas', 'Illinois']

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [190]:


def answer_seven():
    census_df = pd.read_csv('census.csv')
    census_df = census_df[census_df['SUMLEV'] == 50]
    census_df = census_df.set_index(['CTYNAME'])
    
    census_df = census_df[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']]
    return (census_df.max(axis=1)-census_df.min(axis=1)).argmax()
    
#    import numpy as np
#    b = {}
#    for i in census_df.index:
#        a = census_df.loc[i,['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']]
#        b[np.array(a).max()-np.array(a).min()] = census_df.loc[i]['CTYNAME']
#    return b[sorted(b.keys(), reverse=True)[0]]

'Harris County'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [230]:
def answer_eight():
    census_df = pd.read_csv('census.csv')
    census_df = census_df[census_df['SUMLEV'] == 50]
    census_df = census_df[['REGION','CTYNAME','STNAME','POPESTIMATE2014','POPESTIMATE2015']]
    return census_df[((census_df['REGION'] == 1) | (census_df['REGION'] == 2)) &
                      census_df['CTYNAME'].str.startswith('Washington') &
                     (census_df['POPESTIMATE2015'] > census_df['POPESTIMATE2014'])][['STNAME','CTYNAME']]

STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County